### PR TITLE
Update to spec

### PR DESCRIPTION
**Pull request by sblack4**
NO FUNCTIONAL CHANGES

This PR is just for updating this module to be in line with our standards and linters by:
- Alphabetizing everything
- adding new pre-commit and workflow hotness
- add versions (no aws version yet)

I want to possibly make functional changes in a subsequent PR and reference this module in our ECS-cluster module rather than duplicating all the code here, because it's largely the same (and for the DLs)

### CODE REVIEW

**Comment by sblack4** [comment]
@smiller171 These checks are going such rapid development that it would be easier to keep them in a tooling repo somewhere

**Comment by smiller171** [comment]
@sblack4 I think it's going to slow down a bit now, but regardless I'd love to get to that, eventually. Work with what we've got for now.

The latest version is a _significant_ improvement in utility

**Comment by sblack4** [comment]
@smiller171 What is review dog saying? https://github.com/rhythmictech/terraform-aws-asg-rollingupdate/pull/8/checks?check_run_id=805174350

**Comment by smiller171** [comment]
@sblack4 you didn't copy the `.yamllint.yml` file

**Pull request merged**
